### ISSUE TITLE
Possible footgun: Too many types are Copy/Clone

### ISSUE THREAD

**Issue by psychon** [glowcoil/xcb-sys#3]
Random example (but I guess this is more important for `xcb_generic_event_t`:
```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct xcb_generic_reply_t {
    pub response_type: u8,
    pub pad0: u8,
    pub sequence: u16,
    pub length: u32,
}
```
This is bad. If anything ever uses the `Copy` implementation, the result is most likely a broken event since this struct only describes the header of the reply and lots of other important stuff is in the following bytes.

[Apparently](https://rust-lang.github.io/rust-bindgen/nocopy.html) it is possible to disable the generation of `Copy` (but I would also think that `Clone` is dangerous here). I would suggest adding something like this to the `bindgen` invocation.

**Comment by micahrj** [comment]
I will give this some thought. It's definitely subjective, but my impulse is to say that this is not the type of thing that a raw C binding crate should be trying to protect against. My opinion is that unsafe bindings to a C API should 1. represent the C faithfully and 2. apply as few restrictions as possible, and then whatever safe wrapper is built on top can worry about using the Rust type system to prevent incorrect usage.

**Comment by psychon** [comment]
Okay, fine with me. This also did not occur to me, but I did not use this library much. I'll go ahead and close this.

(Also, there are some types where `Copy` is safe (iterators?) and can actually be useful, so just making everything not-`Copy` is not the best solution.)
